@if(isset($post))
	@include('pages.post')
@elseif(isset($video_data) && isset($media))
	@include('pages.media-videos')
@elseif(isset($images) && isset($media))
	@include('pages.media-images')
@elseif(isset($cat) && isset($cat_video_data) && isset($cat_images))
	@include('pages.category')
@elseif(isset($cat_news_show))
	@include('pages.cat-news-show')
@elseif(isset($cat_video_data_show))
	@include('pages.cat-videos-show')
@elseif(isset($cat_images_show))
	@include('pages.cat-images-show')
@elseif(isset($reviews))
	@include('pages.reviews')
@endif